---

- hosts: all
  gather_facts: true
  remote_user: root
  tasks: 

    - name: Update
      raw: apt-get -y --allow-unauthenticated update || true

    - name: Upgrade
      raw: apt-get -y --allow-unauthenticated upgrade

- hosts: minio
  remote_user: root
  roles:
    - atosatto.minio
  vars:
    minio_server_datadirs: [ "/minio-data" ]
    minio_server_make_datadirs: true
    minio_access_key: "{{ access_key }}"
    minio_secret_key: "{{ secret_key }}"
    minio_server_cluster_nodes: 
      - 'http://172.28.4.3:9000'
      - 'http://172.28.4.5:9000'
      
