---

- hosts: minio
  remote_user: root
  roles:
    - atosatto.minio
  vars:
    minio_server_datadirs: [ "/minio-data" ]
    minio_server_addr: ":{{ server_port }}"
    minio_server_make_datadirs: true
    minio_access_key: "{{ access_key }}"
    minio_secret_key: "{{ secret_key }}"
    minio_server_cluster_nodes:

