---

- hosts: all
  gather_facts: false
  remote_user: root
  tasks: 

    - name: Update
      raw: apt-get -y --allow-unauthenticated update || true

    - name: Upgrade
      raw: apt-get -y --allow-unauthenticated upgrade

- hosts: minio
  remote_user: root
  tasks: 

    - name: exec shell
      shell: echo "{{ansible_ssh_host}}" >> /tmp/hostip.log

    - name: Install screen
      apt:
        name: screen
        state: present
        allow_unauthenticated: yes

    - name: Create /usr/local/minio
      file:
        path: /usr/local/minio
        recurse: yes
        state: directory

    - name: Download minio server
      get_url:
        url: https://dl.minio.io/server/minio/release/linux-amd64/minio
        dest: /usr/local/minio/minio
        validate_certs: no

    - name: Make server executable by chmod "+x"
      file: dest=/usr/local/minio/minio mode=a+x

    - name: Install rc.local
      template:
        src: files/rc.local
        dest: /etc/rc.local
        mode: 755

    - name: Finally run rc.local
      command: /etc/rc.local
      
